name: build-and-deploy-portfolio-site

on:
  push:
    branches: [main]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt
          pip install flake8 black
          
      - name: Lint Python with flake8
        run: flake8 generate_html.py

      - name: Format Python with black
        run: black generate_html.py

      - name: Lint Markdown files (optional)
        continue-on-error: true
        run: |
          markdownlint articles/*.md

      - name: Generate HTML from Markdown
        run: python generate_html.py

      - name: Copy assets folder to build directory
        run: |
          cp -r assets build/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          publish_branch: gh-pages
